#!/usr/bin/env python3
"""API Key Harvesting Script.

Safely imports API keys from user's local projects into Me4BrAIn's
central configuration for the Dynamic API Store.
"""

import os
from pathlib import Path
from dataclasses import dataclass

# Source projects with known API keys
SOURCE_PROJECTS = [
    Path("/Users/fulvioventura/endogram"),
    Path("/Users/fulvioventura/fvmc-trade-strategy"),
    Path("/Users/fulvioventura/nba-predictor-streamlit"),
]

# Key mappings: (source_env_var, target_tool_name, description)
API_KEY_MAPPINGS = [
    # Medical / Science
    ("NCBI_API_KEY", "pubmed", "PubMed/NCBI E-utilities"),
    ("NCBI_TOOL_NAME", "pubmed_tool_name", "PubMed Tool Name"),
    ("NCBI_EMAIL", "pubmed_email", "PubMed Contact Email"),
    # Finance
    ("FRED_API_KEY", "fred", "Federal Reserve Economic Data"),
    # Sports / Betting
    ("BALLDONTLIE_API_KEY", "balldontlie", "NBA Stats API"),
    ("THE_ODDS_API_KEY", "odds_api", "Betting Odds Aggregator"),
    ("RAPIDAPI_KEY", "rapidapi", "RapidAPI Hub Gateway"),
    # Search / AI
    ("PERPLEXITY_API_KEY", "perplexity", "Perplexity Search API"),
    ("NANOGPT_API_KEY", "nanogpt", "NanoGPT LLM Provider"),
]


@dataclass
class DiscoveredKey:
    """Represents a discovered API key."""

    key_name: str
    tool_name: str
    description: str
    value: str
    source_project: str


def parse_env_file(env_path: Path) -> dict[str, str]:
    """Parse a .env file into a dictionary."""
    env_vars = {}
    if not env_path.exists():
        return env_vars

    with open(env_path, "r") as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            if "=" in line:
                key, _, value = line.partition("=")
                # Remove quotes if present
                value = value.strip().strip('"').strip("'")
                env_vars[key.strip()] = value
    return env_vars


def harvest_keys() -> list[DiscoveredKey]:
    """Harvest API keys from source projects."""
    discovered = []

    for project_path in SOURCE_PROJECTS:
        env_path = project_path / ".env"
        if not env_path.exists():
            print(f"⚠️  No .env found in {project_path.name}")
            continue

        env_vars = parse_env_file(env_path)
        project_name = project_path.name

        for source_var, tool_name, description in API_KEY_MAPPINGS:
            if source_var in env_vars and env_vars[source_var]:
                discovered.append(
                    DiscoveredKey(
                        key_name=source_var,
                        tool_name=tool_name,
                        description=description,
                        value=env_vars[source_var],
                        source_project=project_name,
                    )
                )

    return discovered


def generate_env_block(keys: list[DiscoveredKey]) -> str:
    """Generate .env block for Me4BrAIn configuration."""
    lines = ["# === AUTO-HARVESTED API KEYS ==="]
    lines.append("# Generated by scripts/harvest_api_keys.py")
    lines.append("")

    # Group by category
    categories = {
        "pubmed": "Medical / Science",
        "fred": "Finance",
        "balldontlie": "Sports",
        "odds_api": "Sports",
        "rapidapi": "Multi-Purpose",
        "perplexity": "Search / AI",
        "nanogpt": "LLM Provider",
    }

    current_category = None
    for key in sorted(keys, key=lambda k: categories.get(k.tool_name, "Other")):
        cat = categories.get(key.tool_name, "Other")
        if cat != current_category:
            lines.append(f"\n# --- {cat} ---")
            current_category = cat

        # Mask key for display (show first 8 and last 4 chars)
        masked = key.value[:8] + "..." + key.value[-4:] if len(key.value) > 12 else key.value
        lines.append(f"# {key.description} (from {key.source_project})")
        lines.append(f"API_STORE_{key.tool_name.upper()}_KEY={key.value}")

    return "\n".join(lines)


def main():
    """Main entry point."""
    print("🔍 Harvesting API Keys from user projects...\n")

    keys = harvest_keys()

    if not keys:
        print("❌ No API keys found!")
        return

    print(f"✅ Found {len(keys)} API keys:\n")
    for key in keys:
        masked = key.value[:8] + "..." + key.value[-4:] if len(key.value) > 12 else "***"
        print(f"  • {key.tool_name}: {key.description}")
        print(f"    Source: {key.source_project} | Key: {masked}")

    print("\n" + "=" * 60)
    print("Generated .env block:\n")
    print(generate_env_block(keys))

    # Write to output file
    output_path = Path(__file__).parent.parent / "data" / "harvested_keys.env"
    output_path.parent.mkdir(exist_ok=True)
    with open(output_path, "w") as f:
        f.write(generate_env_block(keys))
    print(f"\n✅ Saved to {output_path}")


if __name__ == "__main__":
    main()
